### ISSUE TITLE
Rendering order of seismicity layers

### ISSUE THREAD

**Issue by baagaard-usgs** [shaefner-usgs/esc-eq-response#16]
I think the rendering of the earthquake layers should be ordered in time (lowest=historical, then mainshock, highest=aftershocks). This keeps the mainshock from getting buried by lots of historical events. In most cases the mainshock will be sufficient large that its dot won't get too buried by the aftershock dots.

**Comment by shaefner-usgs** [comment]
This requires a bit of "voodoo" because Leaflet doesn't provide much control of layer order (they're rendered in the order they are added, and it's impossible to directly control this b/c layers are added via Ajax requests). 

I came up with a solution that always plots aftershocks on top of historical. For technical reasons, it's easy to to plot the mainshock on top, so the order is: historical, aftershocks, mainshock.

At the same time, I fixed a bug where older events within each layer were plotting on top. Now the newer events always plot above older events.
