### ISSUE TITLE
allow page to load even when feeds are down/timeout

### ISSUE THREAD

**Issue by baagaard-usgs** [shaefner-usgs/esc-eq-response#45]
During the Searless sequence when earthquake.usgs.gov was not responding the app webpage did not fully load when the significant earthquakes feed was down. It was not possible to manually enter an event id and proceed.

**Comment by shaefner-usgs** [comment]
Thanks Brad. It's already on my list of things-to-do.

**Comment by shaefner-usgs** [comment]
Do you have any additional details about what was happening when the app was breaking?

I couldn't replicate this problem because the code already has various fail-safes built-in so that it doesn't bomb when feeds fail to load. I tried everything I could think of that might have happened when earthquake.usgs.gov had connectivity issues following the M7.1 Ridgecrest event:

1. Sending an empty json file
2. Sending an invalid json file (truncated json file; plain text like "404 File Not Found")
3. Sending http error status codes (I tried 301, 401, 403, 404, 500, 501, 502, 503, 504)
4. Forcing a network time-out

In each case, the app failed to load the significant earthquakes feed, but remained fully functional otherwise, allowing the user to enter an event id.

I added a check in the code so that it no longer attempts to render the significant pull down menu if there's no data. Hopefully this will help. In addition, I made the error messages more informative so that there will be more clues about what's happening should this happen again. Like always, there is usually even more details in the javascript console when errors happen (see [PR #46](https://github.com/shaefner-usgs/esc-eq-response/pull/46)).

**Comment by baagaard-usgs** [comment]
Unfortunately, I don't have any more info about what was causing the app to fail. I was on the road traveling, so I didn't have time to dig deeper.
